### 查询AlertLogController分页列表 => 成功
GET {{baseUrl}}/iot/alertLog/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/iot/alertLog/list
Authorization: Bearer {{token}}

### 新增AlertLogController => 成功
POST {{baseUrl}}/iot/alertLog
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/iot/alertLog/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改AlertLogController => 成功
PUT {{baseUrl}}/iot/alertLog
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除AlertLogController => 成功
DELETE {{baseUrl}}/iot/alertLog/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{alertLogIds} => 成功
DELETE {{baseUrl}}/iot/alertLog/{alertLogIds}
Authorization: Bearer {{token}}
