### 查询FunctionLogController分页列表 => 成功
GET {{baseUrl}}/iot/log/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/iot/log/list
Authorization: Bearer {{token}}

### 新增FunctionLogController => 成功
POST {{baseUrl}}/iot/log
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/iot/log/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改FunctionLogController => 成功
PUT {{baseUrl}}/iot/log
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除FunctionLogController => 成功
DELETE {{baseUrl}}/iot/log/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{ids} => 成功
DELETE {{baseUrl}}/iot/log/{ids}
Authorization: Bearer {{token}}
