### 查询SysLoginController分页列表 => 成功
GET {{baseUrl}}/unknown/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询getInfo => 成功
GET {{baseUrl}}/unknown/getInfo
Authorization: Bearer {{token}}

### 查询getRouters => 成功
GET {{baseUrl}}/unknown/getRouters
Authorization: Bearer {{token}}

### 新增SysLoginController => 成功
POST {{baseUrl}}/unknown
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/login => 成功
POST {{baseUrl}}/unknown/login
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改SysLoginController => 成功
PUT {{baseUrl}}/unknown
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除SysLoginController => 成功
DELETE {{baseUrl}}/unknown/1,2,3
Authorization: Bearer {{token}}
