### 查询SysTranslateController分页列表 => 成功
GET {{baseUrl}}/system/translate/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 新增SysTranslateController => 成功
POST {{baseUrl}}/system/translate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/import => 成功
POST {{baseUrl}}/system/translate/import
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/export => 成功
POST {{baseUrl}}/system/translate/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改SysTranslateController => 成功
PUT {{baseUrl}}/system/translate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除SysTranslateController => 成功
DELETE {{baseUrl}}/system/translate/1,2,3
Authorization: Bearer {{token}}
