### 查询SceneModelDataController分页列表 => 成功
GET {{baseUrl}}/scene/modelData/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/scene/modelData/list
Authorization: Bearer {{token}}

### 查询/listByType => 成功
GET {{baseUrl}}/scene/modelData/listByType
Authorization: Bearer {{token}}

### 新增SceneModelDataController => 成功
POST {{baseUrl}}/scene/modelData
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/scene/modelData/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/editEnable => 成功
POST {{baseUrl}}/scene/modelData/editEnable
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改SceneModelDataController => 成功
PUT {{baseUrl}}/scene/modelData
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除SceneModelDataController => 成功
DELETE {{baseUrl}}/scene/modelData/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{ids} => 成功
DELETE {{baseUrl}}/scene/modelData/{ids}
Authorization: Bearer {{token}}
