### 查询CommonPtzController分页列表 => 成功
GET {{baseUrl}}/common/ptz/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 新增CommonPtzController => 成功
POST {{baseUrl}}/common/ptz
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/ptz/{deviceId}/{channelId} => 成功
POST {{baseUrl}}/common/ptz/ptz/{deviceId}/{channelId}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改CommonPtzController => 成功
PUT {{baseUrl}}/common/ptz
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除CommonPtzController => 成功
DELETE {{baseUrl}}/common/ptz/1,2,3
Authorization: Bearer {{token}}
