### 查询SipConfigController分页列表 => 成功
GET {{baseUrl}}/sip/sipconfig/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 新增SipConfigController => 成功
POST {{baseUrl}}/sip/sipconfig
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 修改SipConfigController => 成功
PUT {{baseUrl}}/sip/sipconfig
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除SipConfigController => 成功
DELETE {{baseUrl}}/sip/sipconfig/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{ids} => 成功
DELETE {{baseUrl}}/sip/sipconfig/{ids}
Authorization: Bearer {{token}}

### 执行删除/product/{productIds} => 成功
DELETE {{baseUrl}}/sip/sipconfig/product/{productIds}
Authorization: Bearer {{token}}
