### 查询ModbusParamsController分页列表 => 成功
GET {{baseUrl}}/modbus/params/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/modbus/params/list
Authorization: Bearer {{token}}

### 新增ModbusParamsController => 成功
POST {{baseUrl}}/modbus/params
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/modbus/params/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/addOrUpdate => 成功
POST {{baseUrl}}/modbus/params/addOrUpdate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改ModbusParamsController => 成功
PUT {{baseUrl}}/modbus/params
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除ModbusParamsController => 成功
DELETE {{baseUrl}}/modbus/params/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{ids} => 成功
DELETE {{baseUrl}}/modbus/params/{ids}
Authorization: Bearer {{token}}
