### 查询AppLanguageController分页列表 => 成功
GET {{baseUrl}}/app/language/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/app/language/list
Authorization: Bearer {{token}}

### 新增AppLanguageController => 成功
POST {{baseUrl}}/app/language
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/app/language/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改AppLanguageController => 成功
PUT {{baseUrl}}/app/language
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除AppLanguageController => 成功
DELETE {{baseUrl}}/app/language/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{ids} => 成功
DELETE {{baseUrl}}/app/language/{ids}
Authorization: Bearer {{token}}
