### 查询AppPreferencesController分页列表 => 成功
GET {{baseUrl}}/app/preferences/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/app/preferences/list
Authorization: Bearer {{token}}

### 新增AppPreferencesController => 成功
POST {{baseUrl}}/app/preferences
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/app/preferences/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/addOrUpdate => 成功
POST {{baseUrl}}/app/preferences/addOrUpdate
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改AppPreferencesController => 成功
PUT {{baseUrl}}/app/preferences
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除AppPreferencesController => 成功
DELETE {{baseUrl}}/app/preferences/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{userIds} => 成功
DELETE {{baseUrl}}/app/preferences/{userIds}
Authorization: Bearer {{token}}
