### 查询NewsController分页列表 => 成功
GET {{baseUrl}}/iot/news/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/iot/news/list
Authorization: Bearer {{token}}

### 查询/bannerList => 成功
GET {{baseUrl}}/iot/news/bannerList
Authorization: Bearer {{token}}

### 查询/topList => 成功
GET {{baseUrl}}/iot/news/topList
Authorization: Bearer {{token}}

### 查询/getDetail => 成功
GET {{baseUrl}}/iot/news/getDetail
Authorization: Bearer {{token}}

### 新增NewsController => 成功
POST {{baseUrl}}/iot/news
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/iot/news/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改NewsController => 成功
PUT {{baseUrl}}/iot/news
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除NewsController => 成功
DELETE {{baseUrl}}/iot/news/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{newsIds} => 成功
DELETE {{baseUrl}}/iot/news/{newsIds}
Authorization: Bearer {{token}}
