### 查询DeviceMessageController分页列表 => 成功
GET {{baseUrl}}/iot/message/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 新增DeviceMessageController => 成功
POST {{baseUrl}}/iot/message
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 修改DeviceMessageController => 成功
PUT {{baseUrl}}/iot/message
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除DeviceMessageController => 成功
DELETE {{baseUrl}}/iot/message/1,2,3
Authorization: Bearer {{token}}
