### 查询DeviceUserController分页列表 => 成功
GET {{baseUrl}}/iot/deviceUser/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/iot/deviceUser/list
Authorization: Bearer {{token}}

### 查询/shareUser => 成功
GET {{baseUrl}}/iot/deviceUser/shareUser
Authorization: Bearer {{token}}

### 新增DeviceUserController => 成功
POST {{baseUrl}}/iot/deviceUser
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/addDeviceUsers => 成功
POST {{baseUrl}}/iot/deviceUser/addDeviceUsers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改DeviceUserController => 成功
PUT {{baseUrl}}/iot/deviceUser
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除DeviceUserController => 成功
DELETE {{baseUrl}}/iot/deviceUser/1,2,3
Authorization: Bearer {{token}}
