### 查询DeviceExtParamValueController分页列表 => 成功
GET {{baseUrl}}/iot/deviceExtValue/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/iot/deviceExtValue/list
Authorization: Bearer {{token}}

### 新增DeviceExtParamValueController => 成功
POST {{baseUrl}}/iot/deviceExtValue
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/iot/deviceExtValue/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改DeviceExtParamValueController => 成功
PUT {{baseUrl}}/iot/deviceExtValue
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除DeviceExtParamValueController => 成功
DELETE {{baseUrl}}/iot/deviceExtValue/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{ids} => 成功
DELETE {{baseUrl}}/iot/deviceExtValue/{ids}
Authorization: Bearer {{token}}
