### 查询DeviceJobController分页列表 => 成功
GET {{baseUrl}}/iot/job/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/iot/job/list
Authorization: Bearer {{token}}

### 新增DeviceJobController => 成功
POST {{baseUrl}}/iot/job
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/iot/job/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改DeviceJobController => 成功
PUT {{baseUrl}}/iot/job
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 执行/changeStatus => 成功
PUT {{baseUrl}}/iot/job/changeStatus
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1
}

### 执行/run => 成功
PUT {{baseUrl}}/iot/job/run
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1
}

### 删除DeviceJobController => 成功
DELETE {{baseUrl}}/iot/job/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{jobIds} => 成功
DELETE {{baseUrl}}/iot/job/{jobIds}
Authorization: Bearer {{token}}
