### 查询RuleCmpController分页列表 => 成功
GET {{baseUrl}}/rule/cmp/list?pageNum=1&pageSize=10
Authorization: Bearer {{token}}

### 查询/list => 成功
GET {{baseUrl}}/rule/cmp/list
Authorization: Bearer {{token}}

### 新增RuleCmpController => 成功
POST {{baseUrl}}/rule/cmp
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "测试数据"
}

### 执行/export => 成功
POST {{baseUrl}}/rule/cmp/export
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/exec => 成功
POST {{baseUrl}}/rule/cmp/exec
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/options => 成功
POST {{baseUrl}}/rule/cmp/options
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/cmpOptions => 成功
POST {{baseUrl}}/rule/cmp/cmpOptions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/typeOptions => 成功
POST {{baseUrl}}/rule/cmp/typeOptions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 执行/script/options => 成功
POST {{baseUrl}}/rule/cmp/script/options
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "key": "value"
}

### 修改RuleCmpController => 成功
PUT {{baseUrl}}/rule/cmp
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "name": "更新后的名称"
}

### 删除RuleCmpController => 成功
DELETE {{baseUrl}}/rule/cmp/1,2,3
Authorization: Bearer {{token}}

### 执行删除/{ids} => 成功
DELETE {{baseUrl}}/rule/cmp/{ids}
Authorization: Bearer {{token}}
